### ISSUE TITLE
Refreshing lights

### ISSUE THREAD

**Issue by anthonycastelli** [tatey/LIFXHTTPKit#8]
When I refresh the lights in my list, everything gets scrambled, groups end up as regular light bulbs and vice versa and everything ends up unalphabetized as well. I've tried to manually sort everything again but still have the same issue. Is there something different I am supposed to do?

Here is my fetch/refresh code. 

```
func fetchLights() {
    self.client = Client(accessToken: token)
    self.allLightTargets = self.client.allLightTarget()
    self.allLightScenes = self.client.scenes

    self.rainbowIndicator.hidden = false
    self.rainbowIndicator.startAnimation()
     self.fetch { (errors) -> Void in
          if errors.count > 0 {
              self.messageTextField.hidden = false
              self.messageTextField.stringValue = "An error occured fetching lights. Refresh and try again."
              self.rainbowIndicator.stopAnimation()
          } else {
               self.rainbowIndicator.stopAnimation()
                self.messageTextField.hidden = true
                self.rainbowIndicator.hidden = true
            }
        }
}

func fetch(completionHandler: (([NSError]) -> Void)? = nil) {
        self.sections.removeAll()
        self.client.fetch { (errors) in
            dispatch_async(dispatch_get_main_queue()) {
                if errors.count > 0 {
                    completionHandler?(errors)
                } else {
                    // All Good
                    self.sections.append(Section(name: "All Lights", sectionType: .Lights, children: self.lightTargetsBySortingAlphabetically(self.allLightTargets), scenes: nil))
                    self.sections.append(Section(name: "Groups", sectionType: .Groups, children: self.groupTargetsBySortingAlphabetically(self.allLightTargets), scenes: nil))
                    self.sections.append(Section(name: "Scenes", sectionType: .Scenes, children: nil, scenes: self.client.scenes))
                    completionHandler?([])
                }

                self.organizeSections()
            }
        }
    }
```

After I organize everything like so:

`self.lightTargetsBySortingAlphabetically(self.allLightTargets)`

```
func lightTargetsBySortingAlphabetically(lightTarget: LightTarget) -> [LightTarget] {
        return [lightTarget] + lightTarget.toLightTargets().sort { (lhs, rhs) in
            return lhs.label < rhs.label
        }
    }
```

and then for the groups

```
func groupTargetsBySortingAlphabetically(lightTarget: LightTarget) -> [LightTarget] {
        return [lightTarget] + lightTarget.toGroupTargets().sort { (lhs, rhs) in
            return lhs.label < rhs.label
        }
    }
```

I believe that is a method I copied from your project with the notification center widget. I've checked everything and tried everything I could think of. What I have noticed though is from time to time, the information returned organized and clean, but the collectionView will read it as a jumbled mess. Do you happen to have any ideas?

**Comment by tatey** [comment]
How often is `fetchLights` being called? It looks like the client and all it's state is thrown away when that function is called.

Consider initializaing the client and the root light targets once, outside of that function. `viewDidLoad` or `init` are good candidates.

Consider updating the view by using an observer on the root light target. Whenever the light target changes, the observer fires. Calling fetch will change the light target if the state on the server is different to the state on the client.

**Comment by tatey** [comment]
I don't think this is a problem with the library itself. Closing.
